language: generic

install:
    - sudo apt-get update
    - sudo apt-get install python3-pip 
    - sudo pip3 install tox-travis
    - sudo pip3 install -r requirements.txt
 
script: 
    - flask run &
    - bg
    - tox
    - kill $!



  


